server:
  port: 3344
spring:
  application:
    name: springcloud-config-server #注册进eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/include1/springcloud.git
          search-paths:
            - springcloud
          username: include1
          password: zm963371608
          ignore-local-ssh-settings: true
      label: master
  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka

#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include:  'bus-refresh'
