server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002 #模拟不懂机器上的注册中心
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defauleZone: http://eureka7001:7001/eureka
