server:
  port: 8004
spring:
  application:
    name: consule-provider-payment
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}