server:
  port: 9903
spring:
  application:
    name: springcloud-nacos-consume
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
