server:
  port: 8001
spring:
  application:
    name: springcloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver #8.0以上使用的驱动名称
    url: jdbc:mysql://localhost:3306/db2021?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 'root' #数据库8.0以上密码必须要打引号
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  instance:
    hostname: payment8001
    prefer-ip-address: true
  client:
    #true表示向注册中心注册自己，默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka


#配置eureka的配置

#    druid:
#      test-on-borrow: true
#      test-while-idle: true
#    # 初始化大小，最小，最大
#    initialSize: 5
#    minIdle: 5
#    maxActive: 50
#    # 配置获取连接等待超时的时间
#    maxWait: 60000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zm.springcloud.entities

